name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

anchors:
  steps: &steps
  - uses: actions/checkout@v2
  - name: Build
    run: cargo build --verbose
  - name: Run tests
    run: cargo test --verbose

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps: *steps

  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps: *steps
