# Do_not_edit_directly._See_readme_section_editing_github_workflows

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: run vcvars
        run: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsx86_amd64.bat"'
      - name: clone llvm
        run: git clone --branch llvmorg-11.1.0 --single-branch --no-tags --depth 1 https://github.com/llvm/llvm-project.git llvm-project-min
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
